export const tipIcons = {
  normal: '',
  success: 'check-circle',
  green: 'check-circle',
  error: 'times-circle',
  red: 'times-circle',
  warn: 'exclamation-circle',
  orange: 'exclamation-circle',
  black: '',
  white: '',
};

export const defaultIconMapper = {
  'arrow-left': 'angle-left',
  'arrow-right': 'angle-right',
  'arrow-up': 'angle-up',
  'arrow-down': 'angle-down',
  date: 'calendar-alt',
  more: 'equals',
  close: 'times',
  noData: 'hiking',
  success: 'check',
  loading: 'circle-notch',
  question: 'question-circle',
  error: 'exclamation-circle',
  max: 'expand',
  restore: 'compress',
  min: 'minus',
  filter: 'filter',
  'circle-up': 'arrow-circle-up',
  'circle-down': 'arrow-circle-down',
};
